export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h2>This is the header</h2>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <h2>this is the footer</h2>
        </footer>
      </body>
    </html>
  )
}
